version: '3.9'

services:
    # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    # https://hub.docker.com/r/blacktop/elasticsearch
    # Set passwords on linux: https://www.youtube.com/watch?v=E-kwK88Vxzk&list=PL4Kk-UTQN84doEerRyIW6GjO7-vLoM-Yc&index=9
    # Useful docker commands: https://blog.softwaremill.com/how-to-keep-your-docker-installation-clean-98a74eb7e7b3
    # Local Volume location: \\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes
    # https://edward-cernera.medium.com/deploy-a-multi-node-elasticsearch-instance-with-docker-compose-ef63625f246e
    elasticsearch:
        image: blacktop/elasticsearch:x-pack-7.10.2
        container_name: elasticsearch
        environment:
            ES_JAVA_OPTS: '-Xms512m -Xmx512m'
        restart: 'no'
        ulimits:
          memlock:
            soft: -1
            hard: -1
          nofile:
            soft: 65536
            hard: 65536
        # cap_add:
        #   - ALL
        volumes:         
          - ./elasticsearch/data:/usr/share/elasticsearch/data
          - type: bind
            source: ./elasticsearch/elasticsearch.yml
            target: /etc/elasticsearch/elasticsearch.yml
            #target: /usr/share/elasticsearch/congfig/elasticsearch.yml
            read_only: true
        ports:
          - 9200:9200
          - 9300:9300
        networks:
          - es_network
        logging:
         driver: 'json-file'
         options:
          # limit logs retained on host to 25MB
          max-size: '500k'
          max-file: '5'
 
    
    # https://hub.docker.com/r/blacktop/kibana    
    kibana:
        image: blacktop/kibana:x-pack-7.10.2
        container_name: kibana
        depends_on:
          - elasticsearch
        restart: 'no'
        ports:
          - 5601:5601
        volumes:
          - type: bind
            source: ./kibana/kibana.yml
            target: /usr/share/kibana/config/kibana.yml
            read_only: true
        networks:
          - es_network
        ulimits:
          memlock:
            soft: -1
            hard: -1
        logging:
         driver: 'json-file'
         options:
          # limit logs retained on host to 25MB
          max-size: '500k'
          max-file: '5'

networks:
  es_network:
    driver: bridge
