version: '3.9'

services:
    # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    # https://hub.docker.com/r/blacktop/elasticsearch
    # Set passwords on linux: https://www.youtube.com/watch?v=E-kwK88Vxzk&list=PL4Kk-UTQN84doEerRyIW6GjO7-vLoM-Yc&index=9
    # Useful docker commands: https://blog.softwaremill.com/how-to-keep-your-docker-installation-clean-98a74eb7e7b3
    # Local Volume location: \\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
        #image: blacktop/elasticsearch:x-pack-7.10.2
        container_name: elasticsearch
        environment:         
            - node.name: es01
            - network.host: 0.0.0.0
            - http.port: 9200
            - cluster.name: docker-cluster
            - node.master: true
            - discovery.type: single-node
            - bootstrap.memory_lock: true
            # - http.cors.enabled: true
            # - http.cors.allow-origin: *
            - ES_JAVA_OPTS: "-Xms512m -Xmx512m"
            - elasticsearch.username: elastic
            - elasticsearch.password: pleasechangeme #LfcLo2lDNCHkzwOWI50A
            - xpack.security.enabled: true

        restart: on-failure
        ulimits:
          memlock:
            soft: -1
            hard: -1
          nofile:
            soft: 65536
            hard: 65536
        # cap_add:
        #   - ALL
        volumes:
          #- "./../data/esdata1:/usr/share/elasticsearch/data"
          - /home/mvreede/data/esdata:/usr/share/elasticsearch/data
          - /home/mvreede/docker-config/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
        ports:
          - 9200:9200
        networks:
          - es_network
        logging:
         driver: "json-file"
         options:
          # limit logs retained on host to 25MB
          max-size: "500k"
          max-file: "5"
 
    
    # https://hub.docker.com/r/blacktop/kibana    
    kibana:
      #image: blacktop/kibana:x-pack-7.10.2
      image: docker.elastic.co/kibana/kibana:7.13.4
      container_name: kibana
      environment:
        - SERVER_NAME:'localhost'
        - server.host: 0.0.0.0
        - server.port: 5601
        - ELASTICSEARCH_URL: http://elasticsearch:9200
        - ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        - elasticsearch.username: elastic
        - elasticsearch.password: pleasechangeme #LfcLo2lDNCHkzwOWI50A
        - xpack.security.enabled: true
        #- xpack.encryptedSavedObjects.encryptionKey: "password_of_at_least_32_characters"
      depends_on:
          - elasticsearch
      restart: on-failure
      ports:
        - 5601:5601
      volumes:
          - /home/mvreede/docker-config/kibana.yml:/usr/share/kibana/config/kibana.yml
      networks:
        - es_network
      ulimits:
        memlock:
          soft: -1
          hard: -1
      logging:
       driver: "json-file"
       options:
        # limit logs retained on host to 25MB
        max-size: "500k"
        max-file: "5"
        
volumes:
  esdata:
    driver: local

networks:
  es_network:
    driver: bridge
